name: Trigger Netlify Build

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Netlify Build
      run: |
        curl -X POST -d {} https://api.netlify.com/build_hooks/YOUR_BUILD_HOOK_ID
